[package]
name = "nds-novel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nds-parser = { path = "../nds-parser" }
zip = { version = "0.6.3", default-features = false, features = ["bzip2", "deflate", "sha1", "zstd"] }
